fix compilation error (#17159)
This bug is caused by #17137: an error is thrown when compiling isolation2 in CI:
```
In file included from ../../../src/include/postgres.h:53:0,
                 from pqsignal.c:63:
../../../src/include/utils/elog.h:73:28: fatal error: utils/errcodes.h: No such file or directory
 #include "utils/errcodes.h"
```

This is because there is no `utils/errcodes.h` when `submake-libpq` is building. Let's build
`submake-libpgport` firstly, and then can build `submake-libpq`.

Co-authored-by: Chen Mulong <chenmulong@gmail.com>
Co-authored-by: Xing Guo <admin@higuoxing.com>