Don't report zlib/zstd reloptions error if not validating
```
CREATE TABLE ao_reloptions_t2 (c1 INT) USING ao_row WITH (compresstype=zstd);
SET allow_system_table_mods = on;
UPDATE pg_class SET reloptions = '{foo=bar,compresstype=zlib,compresslevel=3}' WHERE relname = 'ao_reloptions_t2';
SELECT reloptions FROM pg_class WHERE relname = 'ao_reloptions_t2';
                 reloptions
---------------------------------------------
 {foo=bar,compresstype=zlib,compresslevel=3}
(1 row)

DROP TABLE ao_reloptions_t2;
ERROR:  zlib compression is not supported by this build
HINT:  Compile without --without-zlib to use zlib compression.
```

The last commit fixing `validate_and_adjust_options()` missed the error if not
building with zlib or zstd. This commit completes the fix and test case.

	commit 2629212bfe848e1701f97db3a9d441f4c39b0547
	Author: Adam Lee <adam8157@gmail.com>
	Date:   Fri Oct 31 10:48:26 2025 +0800

	    Don't report compresstype error if not validating